[build]
  command = "npm ci --omit=dev"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Map the /api calls to our function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Ensure the frontend works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
